---

- name: Validate sudoers file syntax before applying
  become: true
  ansible.builtin.command: visudo -cf /etc/sudoers
  changed_when: false

- name: Deploy sudoers config for passwordless sudo
  become: true
  ansible.builtin.template:
    src: sudoers.j2
    dest: /etc/sudoers.d/ansible_passwordless_sudo
    owner: root
    group: root
    mode: "0440"
    validate: "visudo -cf %s"