---
- name: "Install/upgrade Helm chart: {{ k8s_common_helm_release_name }}"
  become: true
  kubernetes.core.helm:
    name: "{{ k8s_common_helm_release_name }}"
    chart_ref: "{{ k8s_common_helm_chart_ref }}"
    chart_version: "{{ k8s_common_helm_chart_version | default(omit) }}"
    release_namespace: "{{ k8s_common_helm_namespace }}"
    create_namespace: true
    kubeconfig: "{{ k8s_common_kubeconfig }}"
    values: "{{ k8s_common_helm_values | default({}) }}"