---
- name: Install Calico operator and custom resources
  ansible.builtin.import_tasks: install_operator.yaml

- name: Wait for Calico pods to be ready
  ansible.builtin.import_tasks: wait_for_ready.yaml